[env]
platform = espressif32 @ 6.9.0
board = esp32doit-devkit-v1
framework = arduino
board_build.filesystem = littlefs
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 921600
lib_deps = 
	https://github.com/schreibfaul1/ESP32-audioI2S.git#3.0.0
	https://github.com/Hoogkamer/Arduino_GFX.git
	tzapu/WiFiManager @ ^2.0.17
	https://github.com/Hoogkamer/IRremoteESP8266.git
	mathieucarbou/ESPAsyncWebServer @ ^3.6.0
	https://github.com/igorantolic/ai-esp32-rotary-encoder.git
	bodmer/TFT_eSPI@^2.5.43
build_flags = 
	-D USER_SETUP_LOADED
	-include src/User_Setup.h
	-Wall
	-Wextra
	-Wunused-variable
	-Wuninitialized
	-std=gnu++11

[env:ipod]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
board_build.partitions = partitions.csv
lib_ldf_mode = deep
build_flags = 
	${env.build_flags}
	-D HAS_REMOTE
	-D DECODE_NEC
	-D TFT_ROTATION=0
	-D VOLUME_MAX=72
	-D VOLUME_DEFAULT=25
	-D VOLUME_STEPS=72
	-D CORE_DEBUG_LEVEL=3
	-D CONFIG_ARDUHAL_LOG_COLORS
	-D CONFIG_IDF_TARGET_ESP32
	-D ARDUINO_RUNNING_CORE=1
	-D ARDUINO_EVENT_RUNNING_CORE=1

[env:portable]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
board_build.partitions = partitions.csv
lib_ldf_mode = deep
lib_ignore = IRremoteESP8266
build_flags = 
	${env.build_flags}
	-D HAS_ROTARIES
	-D REVERSE_VOLUME_ENCODER
	-D TFT_ROTATION=1
	-D MONO_OUTPUT
	-D VOLUME_MAX=72
	-D VOLUME_DEFAULT=15
	-D VOLUME_STEPS=72
	-D CORE_DEBUG_LEVEL=3
	-D CONFIG_ARDUHAL_LOG_COLORS
	-D CONFIG_IDF_TARGET_ESP32
	-D ARDUINO_RUNNING_CORE=1
	-D ARDUINO_EVENT_RUNNING_CORE=1

[env:native]
platform = native
lib_ignore = IRremoteESP8266, Ai Esp32 Rotary Encoder, TFT_eSPI, WiFiManager, ESPAsyncWebServer, ESP32-audioI2S-master, GFX Library for Arduino
build_flags = 
	-std=gnu++11
	-D UNIT_TEST
lib_deps = 
	throwtheswitch/Unity@^2.6.1
lib_compat_mode = off
