#pragma once

// IR Remote codes (specific to your cassette remote)
// Auto-generated by programmer script
#define RC_POWER 1223ULL
#define RC_PREVIOUS_STATION 1114ULL
#define RC_NEXT_STATION 1115ULL
#define RC_NEXT_CATEGORY 1113ULL
#define RC_PREVIOUS_CATEGORY 1112ULL
#define RC_TURN_ON_SCREEN 1116ULL
#define RC_SHOW_DETAILS 1233ULL
#define RC_SAVE_STATION 1154ULL
#define RC_RADIO_OFF1 1037ULL
#define RC_RADIO_OFF2 99998ULL
#define RC_RADIO_OFF3 99999ULL
